### ISSUE TITLE
update scheduler.JSON file 

### ISSUE THREAD

**Issue by svarughesehcl** [HCL-TECH-SOFTWARE/appscan-automation-framework#23]
- support scan windows with a array of scanIDs
EX:
{
    "scans": [
        {scanID: "0000000", "start_scan_window": "100920190028", "end_scan_window": "000000000"},
        {scanID: "0000000", "start_scan_window": "100920190028", "end_scan_window": "000000000"}
    ]
}

**Comment by afhcl** [comment]
done
