### ISSUE TITLE
Dast Proxy Server URL Does not Exist

### ISSUE THREAD

**Issue by michael-barone** [HCL-TECH-SOFTWARE/appscan-automation-framework#25]
Please update ReadMe with new URL for Proxy Server. The below URL does not work. 

https://github.com/hclproducts/appscan-automation-framework/blob/master/Extras/AppScan_Proxy_Server/DastProxyServerStandalone.1.1.403.zip

**Comment by afhcl** [comment]
Need to add instructions for downloading proxy server, since it will not be hosted in this repo
