### ISSUE TITLE
Error when launching getPolicyList.js script

### ISSUE THREAD

**Issue by AHebe-ABlogiX** [HCL-TECH-SOFTWARE/appscan-automation-framework#40]
- node.js version : v12.13.1
- OS : windows server 2016
When launching : node getPolicyList.js the following error occurs : 

> Logging into AppScan Enterprise...
> 13:53:37 - debug: Getting all test policies in AppScan Enterprise...
> Logging into AppScan Enterprise...
> 13:53:37 - error: Error trying to get test policies, TypeError: didGetTestPolicies.body.replace is not a function

**Comment by AHebe-ABlogiX** [comment]
Logging into AppScan Enterprise...
14:28:54 - debug: Getting all test policies in AppScan Enterprise...
Logging into AppScan Enterprise...
{"statusCode":500,"body":{"type":"Buffer","data":[60,63,120,109,108,32,118,101,114,115,105,111,110,61,34,49,46,48,34,32,101,110,99,111,100,105,110,103,61,34,85,84,70,45,56,34,32,115,116,97,110,100,97,108,111,110,101,61,34,121,101,115,34,
63,62,60,101,114,114,111,114,77,101,115,115,97,103,101,62,60,101,114,114,111,114,77,101,115,115,97,103,101,62,33,67,82,87,65,69,50,57,57,57,69,32,58,32,84,104,114,101,97,100,32,119,97,115,32,98,101,105,110,103,32,97,98,111,114,116,101,10
0,46,46,32,69,114,114,111,114,32,67,111,100,101,58,67,82,87,65,69,50,57,57,57,69,33,60,47,101,114,114,111,114,77,101,115,115,97,103,101,62,60,47,101,114,114,111,114,77,101,115,115,97,103,101,62]},"headers":{"x-powered-by":"Servlet/3.0","
x-frame-options":"SAMEORIGIN","content-type":"application/xml","content-language":"fr-FR","content-length":"176","connection":"Close","date":"Mon, 09 Dec 2019 13:28:54 GMT"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":nul
l,"host":"win-ktapeaab4em:9443","port":"9443","hostname":"win-ktapeaab4em","hash":null,"search":null,"query":null,"pathname":"/ase/api/testpolicies/all","path":"/ase/api/testpolicies/all","href":"https://win-ktapeaab4em:9443/ase/api/test
policies/all"},"method":"GET","headers":{"Cookie":["asc_session_id=563fd3c7-8c61-4382-96bd-df8236eff54e;Version=0;Path=/ase;Secure;HttpOnly"],"asc_xsrf_token":"563fd3c7-8c61-4382-96bd-df8236eff54e","Accept":"application/xml"}}}
14:28:54 - info: ~~~~~~~~~~
14:28:54 - info: ~Policies~
14:28:54 - info: ~~~~~~~~~~

**Comment by svarughesehcl** [comment]
@AHebe-ABlogiX  could you send us these logs please:
<AppScan Enterprise Home>\Logs\Log.txt
<AppScan Enterprise Home>\Liberty\usr\servers\ase\logs\messages.txt
<AppScan Enterprise Home>\Liberty\usr\servers\ase\logs\console.txt

**Comment by svarughesehcl** [comment]
@AHebe-ABlogiX actually I think I was able to find the error.  I made the fix and pushed it to master.  Can you pull the latest code and see if it solves your error?

**Comment by svarughese91** [comment]
@AHebe-ABlogiX any updates?  Did the fix work for you?

**Comment by svarughesehcl** [comment]
closing, @AHebe-ABlogiX confirmed this is resolved
