### ISSUE TITLE
Create script to list all the scans and the associated scanner and Schedule,

### ISSUE THREAD

**Issue by xeon82** [HCL-TECH-SOFTWARE/appscan-automation-framework#42]
Hi Hcl team, is it possible to have a script for ASE Entreprise to be able to:
Create script to list all the scans and the associated scanner and Schedule, status of the last scan
thank you!!

**Comment by svarughesehcl** [comment]
@xeon82 thanks for reaching out.  At this moment there are no APIs that ASE supports to schedule scans.  The framework utilizes the current ASE APIs.  If this is a feature request you are looking for in the ASE product, I recommend adding it to the RFE here: https://appscan-ideas.hcltechsw.com/
